# MIT License
#
# Copyright (c) 2022 EASE lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Relay Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOOS: linux
  GO111MODULE: on
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-image:
    name: Relay build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.4"

      - name: Setup go dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
          # chmod +x $(go env GOPATH)/bin/*
          # export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: tools/relay/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          target: relay
          tags: vhiveease/relay:latest
          context: .



  integration-tests:
    name: Relay Integration Tests
    needs: build-image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Start container
        working-directory: benchmarks/aes
        run: |
          set -x

          docker-compose -f ./yamls/docker-compose/dc-aes-go.yaml up &> log_file &
          sleep 15

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.4"

      - name: Invoke
        working-directory: tools/invoker
        run: |
          set -x
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          chmod +x $(go env GOPATH)/bin/*
          export PATH="$PATH:$(go env GOPATH)/bin"

          make invoker
          echo '[ { "hostname": "localhost" } ]' > endpoints.json
          ./invoker -port 50000 -dbg
          cat rps*lat.csv

      - name: Show docker-compose log
        working-directory: benchmarks/aes
        run: cat log_file
